// <auto-generated />
namespace QuickCode.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedplantfkfromdtpye : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedplantfkfromdtpye));
        
        string IMigrationMetadata.Id
        {
            get { return "201601091915533_removed plant fk from dtpye"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
